#!/usr/bin/env python3
"""Build deterministic JSON/Markdown; fail before writing if any source is invalid."""
import argparse
from pathlib import Path
import sys

from registry import ROOT, RegistryError, discover, document, json_text, markdown, require_valid


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sources", type=Path, default=ROOT / "sources/repositories.yaml")
    parser.add_argument("--checkouts", type=Path, help="use sibling checkouts instead of offline hash-verified snapshots")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "generated")
    parser.add_argument("--check", action="store_true", help="compare generated bytes with tracked outputs, without writing")
    args = parser.parse_args(argv)
    try:
        entries = discover(args.sources, args.checkouts)
        require_valid(entries)
        payload = document(entries)
        provenance = {e['manifest']['id']: e['provenance'] for e in entries}
        outputs = {"aipe.json": json_text(payload), "aipe.md": markdown(payload, provenance)}
        if args.check:
            for name, content in outputs.items():
                if not (args.output_dir / name).is_file() or (args.output_dir / name).read_bytes() != content.encode("utf-8"):
                    raise RegistryError(f"generated output drift: {name}")
        else:
            args.output_dir.mkdir(parents=True, exist_ok=True)
            for name, content in outputs.items():
                (args.output_dir / name).write_text(content, encoding="utf-8", newline="\n")
        print(f"{'Verified' if args.check else 'Built'} {len(entries)} capabilities")
    except (RegistryError, OSError, UnicodeError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
